# Generated by Django 2.0.6 on 2018-06-20 22:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('name', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('registrationDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('url', models.CharField(blank=True, default='', max_length=250, null=True)),
            ],
            options={
                'db_table': 'applications',
            },
        ),
    ]
