# Generated by Django 2.0.6 on 2018-06-20 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AOR',
            fields=[
                ('name', models.CharField(choices=[(1, 'East'), (2, 'West')], default='', max_length=4, primary_key=True, serialize=False)),
                ('aorId', models.IntegerField(default=0, unique=True)),
                ('centroidX', models.FloatField(blank=True, null=True)),
                ('centroidY', models.FloatField(blank=True, null=True)),
                ('bboxX1Y1', models.FloatField(blank=True, null=True)),
                ('bboxX2Y1', models.FloatField(blank=True, null=True)),
                ('bboxX2Y2', models.FloatField(blank=True, null=True)),
                ('bboxX1Y2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'AreaOfOperations',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('cityId', models.CharField(default='', max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=45)),
                ('zipcode', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('aor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.AOR')),
            ],
            options={
                'db_table': 'cities',
            },
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('countyId', models.CharField(default='', max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=45)),
                ('type', models.CharField(blank=True, max_length=45, null=True)),
                ('centroidX', models.FloatField(blank=True, null=True)),
                ('centroidY', models.FloatField(blank=True, null=True)),
                ('bboxX1Y1', models.FloatField(blank=True, null=True)),
                ('bboxX2Y1', models.FloatField(blank=True, null=True)),
                ('bboxX2Y2', models.FloatField(blank=True, null=True)),
                ('bboxX1Y2', models.FloatField(blank=True, null=True)),
                ('aor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.AOR')),
            ],
            options={
                'db_table': 'counties',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('districtId', models.IntegerField(default=0, unique=True)),
                ('districtCode', models.CharField(default='', max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=45)),
                ('centroidX', models.FloatField(blank=True, null=True)),
                ('centroidY', models.FloatField(blank=True, null=True)),
                ('bboxX1Y1', models.FloatField(blank=True, null=True)),
                ('bboxX2Y1', models.FloatField(blank=True, null=True)),
                ('bboxX2Y2', models.FloatField(blank=True, null=True)),
                ('bboxX1Y2', models.FloatField(blank=True, null=True)),
                ('aor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.AOR')),
            ],
            options={
                'db_table': 'districts',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('name', models.CharField(choices=[(1, 'Atlantic'), (2, 'Capital'), (3, 'Central'), (4, 'HQ'), (5, 'Midwest'), (6, 'Mountain'), (7, 'Northeast'), (8, 'Pacific'), (9, 'Southeast'), (10, 'Southwest')], default=1, max_length=10, primary_key=True, serialize=False)),
                ('regionId', models.IntegerField(default=0, unique=True)),
                ('centroidX', models.FloatField(blank=True, null=True)),
                ('centroidY', models.FloatField(blank=True, null=True)),
                ('bboxX1Y1', models.FloatField(blank=True, null=True)),
                ('bboxX2Y1', models.FloatField(blank=True, null=True)),
                ('bboxX2Y2', models.FloatField(blank=True, null=True)),
                ('bboxX1Y2', models.FloatField(blank=True, null=True)),
                ('aor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.AOR')),
            ],
            options={
                'db_table': 'regions',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('name', models.CharField(default='', max_length=20, primary_key=True, serialize=False)),
                ('stateAbbv', models.CharField(blank=True, max_length=3, null=True)),
                ('stateId', models.IntegerField(blank=True, default=0, null=True, unique=True)),
                ('serviceStatus', models.CharField(choices=[(0, 'Operational'), (1, 'No Office'), (2, 'No Office/No Service')], default='Operational', max_length=45)),
                ('centroidX', models.FloatField(blank=True, null=True)),
                ('centroidY', models.FloatField(blank=True, null=True)),
                ('bboxX1Y1', models.FloatField(blank=True, null=True)),
                ('bboxX2Y1', models.FloatField(blank=True, null=True)),
                ('bboxX2Y2', models.FloatField(blank=True, null=True)),
                ('bboxX1Y2', models.FloatField(blank=True, null=True)),
                ('aor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.AOR')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.Region')),
            ],
            options={
                'db_table': 'states',
            },
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.Region'),
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.State'),
        ),
        migrations.AddField(
            model_name='county',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.District'),
        ),
        migrations.AddField(
            model_name='county',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.Region'),
        ),
        migrations.AddField(
            model_name='county',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.State'),
        ),
        migrations.AddField(
            model_name='city',
            name='county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.County'),
        ),
        migrations.AddField(
            model_name='city',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.District'),
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.Region'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.State'),
        ),
    ]
