# Generated by Django 2.0.6 on 2018-06-20 22:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inmate',
            fields=[
                ('inmateNumber', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('lastName', models.CharField(default='', max_length=50)),
                ('firstName', models.CharField(default='', max_length=50)),
                ('middleName', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('suffix', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=1)),
                ('age', models.IntegerField(default=0)),
                ('race', models.CharField(choices=[('W', 'White'), ('B', 'Black'), ('I', 'Native American/American Indian'), ('H', 'Hispanic'), ('A', 'Asian'), ('O', 'Other'), ('N', '---')], default='N', max_length=1)),
                ('facilityCode', models.CharField(default='', max_length=5)),
                ('facilityName', models.CharField(default='', max_length=90)),
                ('facilityType', models.CharField(default='', max_length=3)),
                ('releaseCode', models.CharField(blank=True, default='', max_length=5, null=True)),
                ('projectedReleaseDate', models.CharField(blank=True, default='', max_length=11, null=True)),
                ('actualReleaseDate', models.CharField(default='', max_length=11)),
                ('caseTags', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'bop_inmates',
            },
        ),
    ]
